version: '3.8'

services:
  # The Laravel application service
  app:
    build:
      context: .
      dockerfile: dockerfile  # Your custom Dockerfile
    container_name: mister_quiz-app  # Change the container name to match your project
    volumes:
      - ./:/var/www/mister_quiz  # Bind mount your app directory
      - ./storage:/var/www/mister_quiz/storage  # Mount the storage directory
      - ./bootstrap/cache:/var/www/mister_quiz/bootstrap/cache  # Bind mount your app directory
    networks:
      - mister_quiz-network
    environment:
      - DB_HOST=db  # Use service name for host to link with MySQL service
      - DB_PORT=3306
      - DB_DATABASE=mister_quiz
      - DB_USERNAME=appuser
      - DB_PASSWORD=userpass

  # The Nginx web server service
  web:
    image: nginx:alpine
    container_name: mister_quiz-nginx  # Custom container name
    ports:
      - "8000:80"  # Expose port 8000 on localhost to port 80 in the container
    volumes:
      - ./:/var/www/mister_quiz  # Bind mount your project directory
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Nginx config
    networks:
      - mister_quiz-network
    depends_on:
      - app  # Nginx starts after the app service

  # The MySQL database service
  db:
    image: mysql:5.7  # You can update this to another MySQL version if needed
    container_name: mister_quiz-mysql  # Custom container name
    environment:
      MYSQL_ROOT_PASSWORD: userpass   # Set the root password
      MYSQL_DATABASE: mister_quiz  # Name of the database
      MYSQL_USER: appuser  # Create a regular user
      MYSQL_PASSWORD: userpass  # Password for the DB user
    volumes:
      - dbdata:/var/lib/mysql  # Persist the database data
    networks:
      - mister_quiz-network
    ports:
      - "3307:3306"  # Expose MySQL to the host, in case you want to access it directly
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-puserpass"]
      interval: 10s
      timeout: 5s
      retries: 3
  composer:
    image: composer:latest
    container_name: mister_quiz-composer
    volumes:
      - ./:/app  # Mount your app directory
    networks:
      - mister_quiz-network
        # phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: mister_quiz-phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: userpass  # Same as your MySQL root password
    ports:
      - "8080:80"  # Access phpMyAdmin on http://localhost:8080
    depends_on:
      - db
    networks:
      - mister_quiz-network

# Define the network
networks:
  mister_quiz-network:
    driver: bridge

# Define the volume for the MySQL data
volumes:
  dbdata:
